Repository List-KR/List-KR, pull requests merged in 2022-04, with the labels that each got.

#273 namu.wiki - Ad ( PowerLink )
  filter-uBO.txt
  filter.txt
  filters-AG/extended_css_ELEMHIDE.txt
  filters-uBO/extended_css_ELEMHIDE.txt
Labels: help wanted, advertisement

#276 feat: ppss.kr /w adshield
  filter-uBO.txt
  filter.txt
  filters-AG/general_extension.txt
  filters-uBO/general_extension.txt
Labels: anti-adblock, advertisement

#280 feat: simple rule for namu.wiki
  filter-uBO.txt
  filter.txt
  filters-AG/extended_css_ELEMHIDE.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-uBO/extended_css_ELEMHIDE.txt
Labels: enhancement, advertisement

#282 Add m.10000recipe.com ad filter
  filter-uBO.txt
  filter.txt
  filter_DNS.txt
  filters-share/adserver_firstparty.txt
  filters-share/general_elemhide.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
Labels: advertisement

#283 add toonkor100.com filter
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
Labels: advertisement

#284 laftel.net - Anti-AdBlock
  filter-uBO.txt
  filter.txt
  filters-AG/antiadblock.txt
  filters-uBO/antiadblock.txt
Labels: anti-adblock

#288 namu.wiki - PowerLink
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: advertisement

#287 ohmynews.com - Ad
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
Labels: advertisement

#292 newspic.kr - Coupang read more advertisement
  filter-uBO.txt
  filter.txt
  filters-AG/general_extension.txt
  filters-share/removeparam.txt
  filters-uBO/general_extension.txt
Labels: advertisement

#293 feat: adshield
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: anti-adblock, advertisement

#295 feat: namu.wiki powerlink
  filter-uBO.txt
  filter.txt
  filters-AG/extended_css_ELEMHIDE.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-uBO/extended_css_ELEMHIDE.txt
Labels: advertisement

#298 feat: adshield (first auto-heuristic patch)
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: anti-adblock, advertisement

#299 fix: humoruniv.com (naver powerlink)
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/scriptlets.txt
Labels: advertisement

#306 feat: namu.wiki
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/extended_css_ELEMHIDE.txt
Labels: enhancement, advertisement

#309 www.tcafe2a.com - Ad
  filter-uBO.txt
  filter.txt
  filters-share/specific_URL.txt
Labels: advertisement

#310 lorem ipsum — slackchat
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: anti-adblock, advertisement, Ad-Shield

#311 Add new powerlink rule and Refactor
  filter-uBO.txt
  filter.txt
  filters-AG/extended_css_ELEMHIDE.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-uBO/extended_css_ELEMHIDE.txt
Labels: advertisement

#314 namu.wiki - Ad ( PowerLink )
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
Labels: advertisement

#315 www.gmarket.co.kr - Ad
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: advertisement

#317 dcinside app video error
  filter.txt
  filters-AG/mobile/android/allowlist_stealth_android_app.txt
Labels: incorrect blocking
