Repository List-KR/List-KR, pull requests merged in 2022-03, with the labels that each got.

#243 filtering mobile coupang, danawa
  filter.txt
  filters/specific_ELEMHIDE.txt
Labels: advertisement

#244 Ad-Shield: inven.co.kr ppss.kr ygosu.com
  filter.txt
  filters/general_extension.txt
  filters/specific_CSS.txt
  filters/specific_ELEMHIDE.txt
Labels: advertisement

#253 namu.wiki - Ad (powerlink update)
  filter.txt
  filters/extended_css_ELEMHIDE.txt
Labels: advertisement

#256 namu.wiki - Ad (powerlink)
  filter.txt
  filters/extended_css_ELEMHIDE.txt
Labels: advertisement

#260 [Needs manual check] ppss.kr - Ad (with various types)
  filter-uBO.txt
  filter.txt
  filters-AG/general_extension.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/general_extension.txt
Labels: advertisement

#261 namu.wiki - Ad ( PowerLink )
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
Labels: advertisement

#264 feat: adshield on ppss.kr
  filter-uBO.txt
  filters-AG/general_extension.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/general_extension.txt
Labels: anti-adblock, advertisement

#266 namu.wiki - Ad ( PowerLink )
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
Labels: advertisement, incorrect blocking

#267 chore: update for incorrect blocking case (inline-tables)
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
Labels: advertisement, incorrect blocking

#268 namu.wiki - Ad ( PowerLink )
  filter-uBO.txt
  filter.txt
  filters-AG/extended_css_ELEMHIDE.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-uBO/extended_css_ELEMHIDE.txt
Labels: advertisement
