Repository List-KR/List-KR, pull requests merged in 2022-06, with the labels that each got.

#393 adcrap
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: anti-adblock, advertisement, Ad-Shield

#394 Ad-Shield
  filter-uBO.txt
  filter.txt
  filters-AG/specific_REDIRECT.txt
  filters-uBO/specific_REDIRECT.txt
Labels: Ad-Shield

#399 Ad-Shield
  filter-uBO.txt
  filter.txt
  filters-AG/antiadblock.txt
  filters-AG/html_filtering.txt
  filters-AG/scriptlets.txt
  filters-AG/specific_REDIRECT.txt
  filters-uBO/antiadblock.txt
  filters-uBO/html_filtering.txt
  filters-uBO/scriptlets.txt
  filters-uBO/specific_REDIRECT.txt
Labels: Ad-Shield

#401 Ensure to hide image on uBO
  filter-uBO.txt
  filter.txt
  filters-uBO/scriptlets.txt
  filters-uBO/specific_CSS.txt
Labels: enhancement, Ad-Shield

#402 coupang new ad parameter
  filter-uBO.txt
  filter.txt
  filters-share/specific_URL.txt
Labels: Ad-Shield

#406 fix breakage on lostark.inven.co.kr
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/scriptlets.txt
  filters-uBO/specific_CSS.txt
Labels: anti-adblock, incorrect blocking, Ad-Shield

#407 obsolete loawa filter
  filter-uBO.txt
  filter.txt
  filters-share/specific_CSS.txt
Labels: Ad-Shield

#408 fix ygosu.com ads
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
Labels: advertisement

#417 newsworker.co.kr - Leftover
  filter-experimental.txt
  filter-uBO-experimental.txt
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: advertisement

#424 Ad - namu.wiki
  experimental/namuwiki/AG.txt
  experimental/namuwiki/uBO.txt
  filter-experimental.txt
  filter-uBO-experimental.txt
Labels: advertisement

#425 namu.wiki - PowerLink
  experimental/namuwiki/AG.txt
  experimental/namuwiki/uBO.txt
  filter-experimental.txt
  filter-uBO-experimental.txt
Labels: advertisement

#427 dpg.danawa.com
  filter-experimental.txt
  filter-uBO-experimental.txt
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/scriptlets.txt
Labels: advertisement

#430 feat: ygosu.com, inven.co.kr
  experimental/adshield/uBO.txt
  filter-uBO-experimental.txt
Labels: anti-adblock, advertisement, ad-shield
