Repository List-KR/List-KR, pull requests merged in 2022-05, with the labels that each got.

#318 www.gmarket.co.kr - invalid rule
  filter-uBO.txt
  filter.txt
  filters-share/allowlist.txt
Labels: incorrect blocking

#319 add onestore version dc app
  filter-uBO.txt
  filter.txt
  filters-AG/mobile/android/allowlist_stealth_android_app.txt
Labels: advertisement

#321 Refresh Ad-Shield
  filter-uBO.txt
  filter.txt
  filters-AG/antiadblock.txt
  filters-share/general_elemhide.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
  filters-uBO/antiadblock.txt
Labels: Ad-Shield

#322 coupang.com - stealth
  filter-uBO.txt
  filter.txt
  filters-AG/allowlist_stealth.txt
Labels: incorrect blocking

#323 m.danawa.com - Ad
  filter-uBO.txt
  filter.txt
  filter_DNS.txt
  filters-AG/scriptlets.txt
  filters-share/adservice_firstparty.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/scriptlets.txt
Labels: advertisement

#324 auth.danawa.com - Ad
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/scriptlets.txt
Labels: advertisement

#326 www.ilogen.com - Ad
  filter-uBO.txt
  filter.txt
  filters-share/specific_URL.txt
Labels: advertisement

#336 fix(ic): happymoney.co.kr (#335)
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: advertisement, incorrect blocking

#337 fix(leftover): dcinside.com (#335, from youslist)
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: advertisement

#340 manaboza06.com - AD
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
Labels: advertisement

#341 www.11st.co.kr, dpg.danawa.com - AD
  filter-uBO.txt
  filter.txt
  filter_DNS.txt
  filters-AG/scriptlets.txt
  filters-share/adservice.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
  filters-uBO/scriptlets.txt
Labels: advertisement

#349 Ad-Shield
  filter-uBO.txt
  filter.txt
  filters-AG/antiadblock.txt
  filters-AG/specific_REDIRECT.txt
  filters-uBO/antiadblock.txt
  filters-uBO/specific_REDIRECT.txt
Labels: Ad-Shield

#351 feat: adshield with safer block
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: Ad-Shield

#352 tgd.kr banner ad
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: advertisement, advertisement user

#353 feat(leftover): inven.co.kr - banner at top
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: advertisement

#357 m.10000recipe.com - Ad
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
Labels: advertisement

#359 login.11st.co.kr - Ad
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
Labels: advertisement

#362 A set of improvements and optimizations
  filter-uBO.txt
  filter.txt
  filters-AG/extended_css_ELEMHIDE.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/extended_css_ELEMHIDE.txt
Labels: enhancement, advertisement, incorrect blocking

#365 Ad-Shield
  filter-uBO.txt
  filter.txt
  filters-AG/antiadblock.txt
  filters-AG/html_filtering.txt
  filters-AG/scriptlets.txt
  filters-uBO/antiadblock.txt
  filters-uBO/scriptlets.txt
Labels: Ad-Shield

#369 Ad-Shield
  filter-uBO.txt
  filter.txt
  filters-share/specific_CSS.txt
Labels: Ad-Shield

#370 Fix loawa. com breakage
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: incorrect blocking, Ad-Shield

#371 Ad-Shield
  filter-uBO.txt
  filter.txt
  filters-AG/antiadblock.txt
  filters-uBO/antiadblock.txt
Labels: Ad-Shield

#372 adcrap: unbreakables
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: anti-adblock, advertisement, Ad-Shield

#373 feat: complete edition
  filter-uBO.txt
  filter.txt
  filters-AG/scriptlets.txt
  filters-uBO/scriptlets.txt
Labels: anti-adblock, advertisement, Ad-Shield

#374 playwares.com - Ad, sign.dcinside.com - Leftover
  filter-uBO.txt
  filter.txt
  filters-AG/specific_CSS.txt
  filters-share/specific_CSS.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
  filters-uBO/specific_CSS.txt
Labels: advertisement

#375 www.ilbe.com - Ad
  filter-uBO.txt
  filter.txt
  filters-share/specific_URL.txt
Labels: advertisement

#380 fix loawa.com issues
  filter-uBO.txt
  filter.txt
  filters-share/extended_css_ELEMHIDE.txt
  filters-share/specific_CSS.txt
Labels: Ad-Shield
