Repository List-KR/List-KR, pull requests merged in 2022-07, with the labels that each got.

#431 newstomato.com - Leftover
  filter-experimental.txt
  filter-uBO-experimental.txt
  filter-uBO.txt
  filter.txt
  filter_DNS.txt
  filters-AG/scriptlets.txt
  filters-share/adservice_firstparty.txt
  filters-share/specific_ELEMHIDE.txt
  filters-uBO/scriptlets.txt
Labels: advertisement

#442 ad: tfreeca22.com and family sites
  filter-experimental.txt
  filter-uBO-experimental.txt
  filter-uBO.txt
  filter.txt
  filter_DNS.txt
  filters-AG/scriptlets.txt
  filters-share/adservice_firstparty.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
  filters-uBO/scriptlets.txt
Labels: advertisement

#445 Ad - casa21.me
  filter-experimental.txt
  filter-uBO-experimental.txt
  filter-uBO.txt
  filter_DNS.txt
  filters-share/specific_ELEMHIDE.txt
  filters-share/specific_URL.txt
Labels: advertisement, nsfw

#450 ad: busan.com (.dia_ad)
  filter-experimental.txt
  filter-uBO-experimental.txt
  filter-uBO.txt
  filter.txt
  filters-share/specific_ELEMHIDE.txt
Labels: advertisement

#452 Ad-Shield
  experimental/adshield/AG.txt
  experimental/adshield/uBO.txt
  filter-experimental.txt
  filter-uBO-experimental.txt
Labels: ad-shield

#462 Ad-Shield tracking
  experimental/adshield/AG.txt
  experimental/adshield/uBO.txt
  filter-experimental.txt
  filter-uBO-experimental.txt
Labels: ad-shield
